<div class="wrap">
    <h1> Footer </h1>
    
    <?php if(isset($data['message'])){ ?>
		<div id="setting-error-settings_updated" class="updated settings-error notice is-dismissible"> 
	        <p><strong><?php echo $data['message'] ?></strong></p>
	        <button type="button" class="notice-dismiss">
	            <span class="screen-reader-text">Dismiss this notice.</span>
	        </button>
	    </div>
    <?php } ?>
     
    <form method="post" action='' enctype="multipart/form-data">
    	<table class="form-table">
            <tbody>
            	<tr>
		            <th><label> Api data <span style="color:red;">*</span> : </label></th>
		            <td>
		            	<input type="text" class="regular-text" name="api" value="<?php echo $data['api']; ?>"  placeholder="Please enter your api code"/>
	            	</td>
		        </tr>

	        </tbody>
        </table>
        <input type="submit" name="submit" id="mp-btn-change" class="button button-primary" value="Save Changes">
    </form>
</div>
